uploads = []
outputs = []

[[generated]]
id = "fYrUYJxT4GDrFkqRK7TMT"
uri = "file://artifacts/emerald/public/images/personas/startups.png"
type = "image"
title = "generated_image"

[[generated]]
id = "YdVzP-dSCYM4QWD5NGN2O"
uri = "file://artifacts/emerald/public/images/personas/faith.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SgPEr9Z58D9ITwOPawLjJ"
uri = "file://artifacts/emerald/public/images/personas/schools.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zUpEyAlVu988Ks3uHGPBV"
uri = "file://artifacts/emerald/public/images/personas/small-business.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2aJbQBeCjKmpCMErCG4xa"
uri = "file://artifacts/emerald/public/images/personas/healthtech.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ks2vcNXXmTeySIniNYYM5"
uri = "file://artifacts/emerald/public/images/personas/fintech.png"
type = "image"
title = "generated_image"
